sudo : required
services :
   - docker

   
before_install :
   - docker build -t scingiraj/docker-react -f Dockerfile.dev .

script :
  - docker run scingiraj/docker-react npm run test -- --coverage
  - docker run -e CI=true [scingiraj/docker-react] npm run test -- --watchAll=false
  
  